import { v4 as uuidv4 } from "uuid";

export const category = [
  {
    _id: 1,
    title: "Kezelőegységek",
  },
  {
    _id: 2,
    title: "Röntgendiagnosztika",
  },
  {
    _id: 3,
    title: "Sterilizálás",
  },
  {
    _id: 4,
    title: "Kézidarabok",
  },
  {
    _id: 5,
    title: "Implantológiai berendezések",
  },
  {
    _id: 6,
    title: "Elszívók-Kompresszorok",
  },
  {
    _id: 7,
    title: "Operációs lámpák",
  },
  {
    _id: 8,
    title: "Kiegészítők",
  },
  {
    _id: 9,
    title: "Ápolás és karbantartás",
  },
  {
    _id:10,
    title:"Egyéb berendezések"
  }
];

export const products = [
  {
    _id: uuidv4(),
    name: "S200",
    image: "/images/S200.jpeg",
    image2: "/images/S200(2).jpeg",
    image3: "/images/S200(3).jpeg",
    image4: "/images/S200(4).jpeg",
    image5: "/images/S200(5).jpeg",
    slug: "produktum 1",
    category: "Kezelőegységek",
    subcategory:"Stern Weber",
    desc: "Megbízhatóság, minőség, ergonómia.",
    desc2: "Teljes körű kényelem: A Stern Weber márka minden jellegzetes tulajdonságával az S200 modell - fogszabályozó orvosoknak készült verziója is - a beteg kényelmének maximalizálására lett kialakítva.",
    desc3: "Az Ön szakmai fejlődésének partnere: Az S200 jóval meghaladja kategóriájának többi képviselőjét, és biztosítja a legújabb Stern Weber által kifejlesztett újításokat: beépítheti az opcionális, könnyen használható funkciókat és speciális eszközöket, amelyek a szakmai színvonalat a következő szintre emelik.",
    desc4: "Számos bővítési lehetőséget biztosít: A higiéniai rendszerek széles választékának, az eszközöknek és az opcionális multimédiás alkalmazásoknak köszönhetően a fogorvosok testre szabhatják az S200-at az egyéni igényeknek megfelelően, és élvezhetik a számtalan élvonalbeli eszköz teljes élményét.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "S300",
    image: "/images/S300.jpeg",
    image2: "/images/S300(2).jpeg",
    image3: "/images/S200(3).jpeg",
    image4: "/images/S200(4).jpeg",
    image5: "/images/S200(5).jpeg",
    slug: "produktum 2",
    category: "Kezelőegységek",
    subcategory: "Stern Weber",
    desc: "Folyamatos innováció, tökéletes integráció, több lehetőség.",
    desc2: "Innovatív irányítás: A fogorvos szakemberek számára munkájukhoz teljes kényelmet biztosít, ez az oka annak, hogy az S300 tartalmazza a legújabb fogászati technológiákat, mint például az új 7 hüvelykes multitouch kijelzőt, mely a nagy teljesítményű mikroprocesszornak köszönhetően maximalizálja a dinamikus eszközök és az integrált rendszerek vezérlését.",
    desc3: "Ergonómia és komfort: A fogászati egység és a korszerűen kialakított betegszék modern kompaktsága mellett az S300-at úgy tervezték, hogy az exkluzív ergonómia - például a háttámla mozgatása esetén a bevilágított terület nem változik (sliding-system) - és a páciens kényelmének példátlan szintjét kínálja.",
    desc4: "Multimédia rendszer: Az S300 kiegészíthető a fogászati egységbe integrált rendszerek széles választékával. A fejlett röntgendiagnosztika, a HD képalapú kommunikációs rendszer és az összes minősített higiéniai eszköz kombinációja teszi az S300-at egy komplett, integrált kezelőközponttá, amely a legigényesebb fogorvos számára is megfelelő." ,
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    image: "/images/S220TRfelso.jpeg",
    image2: "/images/S220TRalso.jpeg",
    image3: "/images/S220TR(3).jpeg",
    image4: "/images/S220TR(4).jpeg",
    image5: "/images/S220TR(5).jpeg",
    slug: "produktum 3",
    name: "S220TR",
    subcategory: "Stern Weber",
    category: "Kezelőegységek",
    desc: "Sokoldalúsága a legjobb, a tökéletes ergonómiai megoldás minden kezelési stílushoz.",
    desc2: "Ergonómia: Integrált kezelőközpont padlóra szerelt vizesegységgel, melyet olyan fogorvosok számára terveztek, akik rugalmas, megbízható, különböző funkciókkal felszerelt és csúcsminőségű tartozékokkal rendelkező fogászati kezelőegységet szeretnének, hogy minden igénynek megfeleljen.",
    desc3:"Teljesítmény-irányítás: Instrument vezérlőpanel LCD érintőképernyővel az eszközök és a fogászati egység funkcióinak felhasználóbarát vezérlésére. A beállítások azonnal és könnyen olvashatók és vezérelhetők; ezen kívül az adatok / funkciók bősége lehetővé teszi a felhasználók számára a fejlett endodonciai kezelések elvégzését.",
    desc4:"Az integráció széleskörű választéka: Az S220TR széles körű exkluzív tartozékokkal rendelkezik, hogy maximalizálja a kényelmet mind a beteg, mind a fogorvos számára: fejlett higiéniai rendszerek a szennyeződés kockázatának kiküszöbölésére és egy beépített rendszer, amely a legmodernebb röntgen diagnosztikai eszközökből áll.",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "S320TR",
    image: "/images/S320TR.jpeg",
    image2: "/images/S320TR(2).jpeg",
    image3: "/images/S320TR(3).jpeg",
    image4: "/images/S320TR(4).jpeg",
    image5: "/images/S320TR(5).jpeg",
    slug: "produktum 4",
    category: "Kezelőegységek",
    subcategory: "Stern Weber",
    desc: "Tiszta innováció a fogorvosoknak.",
    desc2: "Az innováció ereje: A legfejlettebb technológia, melyet a fogorvos igényeit teljesen ismerő személyek nagy gondossággal hoztak létre.  Az új S320TR egy nagy teljesítményű multitouch 7 hüvelykes kijelzővel rendelkezik, amely maximalizálja a dinamikus eszközök és az integrált rendszerek vezérlését.",
    desc3: "Inspiráló ergonómia: Kompakt kialakítás, könnyebb kulcsfontosságú elemek, exkluzív ergonómiai koncepciók: az új S320TR a fogászati team számára sok előnnyel rendelkezik. Ezenkívül a betegszék - a modern vonalakkal, független vagy szinkronizált mozgásokkal és a háttámla mozgatása esetén a bevilágított terület nem változik (sliding-system)",
    desc4: "Maximális potenciál: Maximális klinikai teljesítmény azok számára, akik gyakorolják a konzervatív fogászat, az implantológia és az endodonciális kezelések területén tevékenykednek. Az S320TR egy komplett integrált kezelőközpont, mely megfelel egy vagy több fogorvos számára is, akik egyazon rendelőben dolgoznak.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "S280TRC",
    image: "/images/S280TRCfelso.jpeg",
    image2: "/images/S280TRC(2).jpeg",
    image3: "/images/S280TRC(3).jpeg",
    image4: "/images/S280TRC(4).jpeg",
    image5: "/images/S280TRC(5).jpeg",
    slug: "produktum 5",
    category: "Kezelőegységek",
    subcategory: "Stern Weber",
    desc: "Magas szintű felszereltség, kényelem.", 
    desc2: "Mindent az új 7 hüvelykes multi-touch kezelőpanellel irányíthat. A fogászat bármely ágában tevékenykedő fogorvos élvezheti a fejlett irányítórendszer előnyeit, amely kiterjed a speciális kezelésekre, mint például az endodoncia és az implantológia.",
    desc3: "Speciális igényekhez igazítható: Az innovatív funkciók és az integrált rendszerek lehetővé teszik a személyre szabott konfigurációkat. A készülék különleges kialakítása felfüggesztett páciensszékkel a fogorvosi team számára exkluzív ergonómiát kínál és a páciens kényelmét is biztosítja.",
    desc3: "Integrált multimédia: A nagy felbontású röntgen diagnosztikai és a vizuális kommunikációs rendszerek egészítik ki a választási lehetőségeket, biztosítva az S280TRC működéséhez az összes szükségest eszközt, melyek minden fogorvos számára nélkülözhetetlenek.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "S380TRC",
    image: "/images/S380TRC.jpeg",
    image2: "/images/S380TRC(2).jpeg",
    image3: "/images/S380TRC(3).jpeg",
    image4: "/images/S380TRC(4).jpeg",
    image5: "/images/S380TRC(5).jpeg",
    slug: "produktum 6",
    category: "Kezelőegységek",
    subcategory: "Stern Weber",
    desc: "Exkluzív innováció, a technológia csúcsa.",
    desc2: "A precíziós és a technológiai újítások kombinációja, az S380TRC egy, a kategóriájában egyedülálló betegszéket kínál. Szinkronizált mozgásokkal és laterális ülésfordulással minden funkció kiváló kényelmet biztosít minden kezelési helyzetben.",
    desc3: "Tökéletes egyensúly: Az S380TRC-ben a beteg és a fogorvosi személyzet kényelmét és az élvonalbeli teljesítményt kombinálták. Kompakt design, könnyített kulcs-elemek és exkluzív ergonómiai koncepciók, mind tökéletes egyensúlyban.",
    desc4: "Tökéletesség a folyamatos fejlődésben: Olyan kezelőegység, amely megfelel minden speciális klinikai igénynek. Az új konzol 7 hüvelykes érintőképernyős kijelzővel és egy erős mikroprocesszorral, a dinamikus műszerek és az integrált rendszerek maximális vezérlésére – ez az S380TRC szíve és lelke.",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "T7",
    image: "/images/T7.jpg",
    slug: "produktum 7",
    category: "Kezelőegységek",
    subcategory: "Orvosi/asszisztensi szék",
    desc: "Az új T7 szék kölcsönhatásba lép a test anatómiájával, megkönnyítve a fogorvos munkáját azáltal, hogy mindig segíti a helyes testtartást.",
    desc2: "A kiváló minőségű anyagok és az innovatív kialakítás biztosítja, hogy a kezelés mindig optimális körülmények között történjen. A puha, könnyen fertőtleníthető anyagból készült kényelmes ülés segíti a fogorvosokat a lábak és a hát megfelelő helyzetében a kezelés során.",
    desc3: "Az S-sorozatú fogorvosi székek orvosi használatra tervezett kiegészítők, amelyek biztosítják, hogy a fogorvos vagy az asszisztens megfelelő támogatást kapjon a fogászati kezelések során. Megfelel az ISO 7493 szabványnak.", 
    desc4: "A megengedett legnagyobb terhelés 135 kg. Ülésmagasság állítás, dönthető deréktámasz, állítható háttámla magasság",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "T8",
    image: "/images/T8.jpeg",
    slug: "produktum 8",
    category: "Kezelőegységek",
    subcategory: "Orvosi/asszisztensi szék",
    desc: "A T8 szék tökéletes támogatást nyújt még hosszú kezelések során is, miközben teljes mozgásszabadságot biztosít minden irányban.",
    desc2: "A beállítási és személyre szabási mechanizmusok leegyszerűsítik a rendelő elrendezéséhez való alkalmazkodást és növelik a kezelő hatékonyságát.", 
    desc3: "Az S-sorozatú fogorvosi székek orvosi használatra tervezett kiegészítők, amelyek biztosítják, hogy a fogorvos vagy az asszisztens megfelelő támogatást kapjon a fogászati kezelések során.", 
    desc4: "Megfelel az ISO 7493 szabványnak. A megengedett legnagyobb terhelés 135 kg. Ülésmagasság állítás, megfordítható háttámla/ karfa",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "T9",
    image: "/images/T9.jpeg",
    slug: "produktum 9",
    category: "Kezelőegységek",
    subcategory: "Orvosi/asszisztensi szék",
    desc: "A forradalmi nyeregszerű geometriának köszönhetően a T9 a nagyon kis helyigényt páratlan kényelemmel párosítja.", 
    desc2: "A lábak függőleges, nyitott helyzete megkönnyíti a páciens megközelítését és a megfelelő háttartás megtartását. Ez csökkenti a fáradtságot, még hosszan tartó kezelés során is üléseken.",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "Myray Hy-Scan szenzor",
    image: "/images/hyscan.jpeg",
    slug: "produktum 10",
    category: "Röntgendiagnosztika",
    subcategory: "Foszforlemezes digitalizáló",
    desc: "Automata foszforlemezes- röntgendigitalizáló, mely magas képminőséget garantál, számítógéphez USB-vel csatlakoztatható.", 
    desc2: "Kompakt méretű, könnyen használható készülék. ",
    desc3: "A hajlítható foszforlemeznek köszönhetően jobban pozícionálható. 4 féle lemezméret: 0 méret: 22 x 31 mm, 762 x 1024 pixel, ",
    desc4: "1 méret: 24 x 40 mm, 792 x 1321 pixel, 2 méret: 31 x 41 mm, 1024 x 1354 pixel, 3 méret: 27 x 54 mm, 891 x 1783 pixel. Kezelőprogram: iRYS",
    amount: 1,
    price: 0,
  },
  {
    _id: uuidv4(),
    name: "RXDC eXTend",
    image: "/images/rxdcextend.jpeg",
    image2: "/images/rxdcextend(2).jpeg",
    image3: "/images/rxdcextend(3).jpeg",
    image4: "/images/rxdcextend(4).jpeg",
    image5: "/images/rxdcextend(5).jpeg",
    slug: "produktum 11",
    category: "Röntgendiagnosztika",
    subcategory: "Intraorális röntgen",
    desc: "Maximális képminőség, minimális dózis. ",
    desc2: "Vezetékes vagy vezeték-nélküli exponálóval. Különleges rugalmasság a vezeték-nélküli vezérlésnek köszönhetően.", 
    desc3: "Mindössze 0,4mm fókusz-pont (30 cm-es távolságból) a még élesebb képért és a még precízebb részletekért. 40, 60 vagy 90 cm-es karral. Kezelőprogram: iRYS",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "RXDC Hypersphere",
    image: "/images/rxdchypersphere.jpeg",
    image2: "/images/rxdchypersphere(2).jpeg",
    image3: "/images/rxdchypersphere(3).jpeg",
    image4: "/images/rxdchypersphere(4).jpeg",
    image5: "/images/rxdchypersphere(5).jpeg",
    slug: "produktum 12",
    category: "Röntgendiagnosztika",
    subcategory: "Intraorális röntgen",
    desc: "Vezeték-nélküli exponálás, innovatív gömbcsuklós felfüggesztés a maximális rugalmasság élményéért.", 
    desc2: "Mindössze 0,4mm fókusz-pont (30 cm-es távolságból) a még élesebb képért és a még precízebb részletekért.", 
    desc3: "40, 60 vagy 90 cm-es karral. ",
    desc4: "Stern Weber kezelőegységre integrálható verzióban is elérhető, a páciens még teljesebb kényelméért! Kezelőprogram: iRYS",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "Szenzor-X-POD",
    image: "/images/xpod.jpeg",
    slug: "produktum 13",
    category: "Röntgendiagnosztika",
    subcategory: "Intraorális Szenzorok",
    desc: "Megerősített kábel, zárt és akadásmentes visszacsatolás, edzett külső borítás, lekerekített sarkok, vékony profil.",
    desc2: "Megbízható és tartós, két méretben kapható: #1 sensor – 20x30mm aktív terület és #2 sensor – 26x34mm aktív terület. Kezelőprogram: iRYS",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "Szenzor-Zen-X",
    image: "/images/zenx.jpeg",
    slug: "produktum 14",
    category: "Röntgendiagnosztika",
    subcategory: "Intraorális Szenzorok",
    desc: "Ergonomikus design, vékony profil, lekerekített sarkok és flexibilis kábel. ",
    desc2: "HD szenzor, mely többrétegű (CsI + FOP + CMOS). ",
    desc3: "Számítógéphez USB-vel csatlakoztatható az azonnali kép-megjelenítésért. ",
    desc4: "Két méretben kapható: #1 szenzor – 24,9x38,9mm és #2 szenzor – 30,4x41,9mm. Kezelőprogram: iRYS",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "CU-2 HD",
    image: "/images/cu2hd.jpeg",
    slug: "produktum 15",
    category: "Röntgendiagnosztika",
    subcategory: "Intraorális Kamera",
    desc: "HD (16:9) felbontású intraorális kamera, mely akár a Stern Weber kezelőegységbe is integrálható. 8 LED, 7 magas tisztaságú üveglencse (F/8), 50-szeres nagyítás. ",
    desc: "Multifunkciós gomb dinamikus nagyítással, széles látószög (90°) Számítógéphez USB-vel csatlakoztatható",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "X5 2D",
    image: "/images/x52dsima.jpg",
    slug: "produktum 16",
    category: "Röntgendiagnosztika",
    subcategory: "Digitális panorámaröntgen",
    desc: "Könnyű 2D diagnosztika a könnyű és kompakt, falra függeszthető/álló rendszerrel. ",
    desc2:" Egy-kattintásos PAN vizsgálat MRT és automatikus legjobb fókusz-választás technológiával. Quick-Scan 6,6 sec. Kezelőprogram: iRYS",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "X5 3D",
    image: "/images/x53dsima.jpg",
    slug: "produktum 17",
    category: "Röntgendiagnosztika",
    subcategory: "Digitális panorámaröntgen",
    desc: "Könnyű 3D/2D diagnosztika a könnyű és kompakt, falra függeszthető/álló rendszerrel.", 
    desc2: "3D MultiFOV rendszer: Ultra-magas felbontású CBCT vizsgálat (80qm) 10x10 FOV maximális mérettel egyetlen felvétellel, vagy MultiFOV felvétel készítése az adott terület exponálásának csökkentésével.",
    desc3: "Quick-Scan 6,4 sec. Kezelőprogram: iRYS",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "X9 Pro",
    image: "/images/x9prosima.jpeg",
    image2: "/images/x9prosima(2).jpeg",
    image3: "/images/x9prosima(3).jpeg",
    slug: "produktum 18",
    category: "Röntgendiagnosztika",
    subcategory: "Digitális panorámaröntgen",
    desc: "Innováció, erő és sokoldalúság.", 
    desc2: "Könnyen fejleszthető bármilyen konfigurációra. ",
    desc3: "HD MultiPAN vizsgálat 5 különböző fókuszponttal. Opcionális Full Touch 10 hüvelykes irányítópanel. QuickPAN 6sec. Kezelőprogram: iRYS",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "X9 Pro CB3D",
    image: "/images/x9procb3d.jpeg",
    slug: "produktum 19",
    category: "Röntgendiagnosztika",
    subcategory: "Digitális panorámaröntgen",
    desc: "Innováció, erő és sokoldalúság. ",
    desc2: "Könnyen fejleszthető bármilyen konfigurációra.", 
    desc3: "Multi FOV. 4x4 - 13x16cm (opcionális). Extrém magas felbontás (68qm). Gyors CB3D scan (3,6-6,4 sec).", 
    desc4: "Fül, orr, torok és sinusok vizsgálata FOG szakorvosok számára. Opcionális Full Touch 10 hüvelykes irányítópanel. Kezelőprogram: iRYS",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "X9 Pro CEPH",
    image: "/images/x9proceph.jpeg",
    slug: "produktum 20",
    category: "Röntgendiagnosztika",
    subcategory: "Digitális panorámaröntgen",
    desc: "Innováció, erő és sokoldalúság. ",
    desc2: "Könnyen fejleszthető bármilyen konfigurációra.", 
    desc3: "Ultra-gyors szkennelés, áthelyezhető PAN/CEPH szenzor vagy opcionálisan két szenzor.", 
    desc4: "Opcionális Full Touch 10 hüvelykes irányítópanel. QuickCEPH 3,3sec. Kezelőprogram: iRYS",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "SW 17,22,28 literes",
    image: "/images/swautoklav.jpeg",
    slug: "produktum 21",
    category: "Sterilizálás",
    subcategory: "Stern Weber autokláv",
    desc: "Az SW autokláv leegyszerűsíti a kezelő munkáját, optimalizálja az időt és a költségeket.", 
    desc2: "A minőség és a magas szintű funkciók biztosítják a biztonságot, megbízhatóságot és a könnyű használatot a monokróm kijelző és billentyűzet segítségével.", 
    desc3: "Beépített Wi-Fi-vel rendelkezik. 17, 22, 28 literes kivitelben",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "SW Platinum 17,22,28 literes",
    image: "/images/swautoklavplatinum.jpeg",
    slug: "produktum 22",
    category: "Sterilizálás",
    subcategory: "Stern Weber autokláv",
    desc: "50 sterilizációs ciklus mindössze 5 liter csapvízzel!", 
    desc2:"A fogyasztása kb. 100ml víz/ciklus.", 
    desc3:"Kifejlesztették az első zárt-hurkú sterilizátort, amely egy speciális belső szűrőrendszert használ, amely a következő ciklusokban is újrahasznosítja a vizet.", 
    desc4:"Ez a teljesítmény kiküszöböli a pazarlást, csökkenti a költségeket és biztosítja a modern fogászati műtétek hatékonyságának jelentős növekedését.", 
    desc5:"A demineralizált víz tárolásával és ellátásával kapcsolatos valamennyi kérdést is megoldja. ", 
    desc6:"A 7 hüvelykes nagyméretű érintőképernyő, amely az autokláv közepén helyezkedik el, lehetővé teszi, hogy egyszerűen és intuitívan használhassa, mint egy tabletet.", 
    desc7:"A felhasználónak állandó hozzáférése van a szükséges adatokhoz, és megtekintheti az összes hasznos információt a képernyőn. 17, 22, 28 literes kivitelben",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "SW Plus 17,22,28 literes",
    image: "/images/swautoklavplus.jpeg",
    slug: "produktum 23",
    category: "Sterilizálás",
    subcategory: "Stern Weber autokláv",
    desc: "Az integrált demineralizáló szűrőnek köszönhetően az SW-PLUS csapvízzel működhet önálló géppel.", 
    desc2: "Ez a modell 4,3 hüvelykes érintőképernyővel rendelkezik. Az SW-PLUS sterilizátor egy intelligens és alapvető munkaeszköz, amely kiváló színvonalat képvisel a színes LCD érintőképernyőnek és a felhasználóbarát felületnek is köszönhetően. ",
    desc3: "Minden parancs megfelel a megjelenő ikonoknak, amelyek biztosítják a gép állapotának azonnali visszajelzését. 17, 22, 28 literes kivitelben",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Aura B",
    image: "/images/aurab.jpg",
    slug: "produktum 24",
    category: "Sterilizálás",
    subcategory: "Tecno-Gaz autokláv",
    desc: "Egy exkluzív lehetőség, amely biztosítja az időmegtakarítást, a közvetlenség és a maximális támogatást az üzemeltetőnek. ", 
    desc2: "Internet kapcsolattal közvetlenül Tecno-Gaz által üzemeltetett honlapon keresztül elérhetőek az autokláv technikai frissítései. Ez a megoldás lehetővé teszi a folyamatos frissítést. ",
    desc3: "Internet kapcsolat szükséges a távoli segítségnyújtás érdekében. Az autokláv rögzíti a funkcionális adatokat, és a rendszer tevékenységeket tárolja belső flash memórián, elküldi az összes összegyűjtött adatot és a Tecno-Gaz szerver automatikusan elemzi a helyes működését.", 
    desc4: "Ha szükséges a távoli segítségnyújtás szolgáltatás aktiválódik, anélkül, hogy a felhasználó kérné, ez a rendkívüli hatékony megoldás biztosítja az operatív biztonságot.",
    desc5: "Tápfeszültség: 230 ± 10% VAC, Maximális áram biztosítékok: 10 A, Tápfeszültség jelentése: 50-60 Hz, Maximális elektromos elnyelt: 1700 W, Nettó tömege termék: 61 Kg. Termék szélessége: 504mm. Termék magassága: 400mm. Termék mélysége: 640mm. Kezdő év a gyártási és forgalmazási: 2009.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Europa B Evo",
    image: "/images/EuropaBEvo.jpg",
    slug: "produktum 25",
    category: "Sterilizálás",
    subcategory: "Tecno-Gaz autokláv",
    desc: "Az Europa B Evo egy utolsó generációs autokláv, amelyet a Tecno-Gaz kutatási iroda és más fontos fejlesztési struktúrák együttműködésével fejlesztettek ki.", 
    desc2: "Jellemzők:",
    desc3:" AISI 304 rozsdamentes acélból készült kezelt kör alakú kamra. Maximális terhelés ciklusonként 5 kg. 3 biztonsági berendezés az ajtón: elektromágneses, elektromos, dinamikus.",
    desc4: "A vezérlőkártya be van helyezve a táblába. Grafikus kijelző. Automatikus légköri beállítási rendszer. Szivattyúval működtetett vízfeltöltő rendszer automatikus leállításával, amikor a tartály megtelt. Ajtótömítés a maximális időtartam biztosítása érdekében.", 
    desc5: "Gyújtólap előszerelésekkel és automatikus víz feltöltéssel és ürítéssel. A berendezésbe beépített erkélyes szellőztető rendszer. Védett tálcatartó.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Europa B Pro",
    image: "/images/EUROPABpro.jpg",
    slug: "produktum 26",
    category: "Sterilizálás",
    subcategory: "Tecno-Gaz autokláv",
    desc: "Az Europe B Pro új elektronikus  vezérléssel és a legújabb generációs mikroprocesszorral felszerelve működik.", 
    desc2: "Sterilizálás ciklus 121 ° C-134 ° C-on egyaránt alkalmas anyagok csomagolt, és kicsomagolt állapotban. Az új hűtési rendszer kettős testű radiátor. Előtaggal ciklusok, amelyeket nem lehet manipulálni. Minden ciklus előre be van állítva, és garantálják a biztonságos sterilizálást a kezelt anyagoknál minden alkalommal.",
    desc3: "Nincs lehetőség a beavatkozásra és a manipulációra üzemeltetői ciklusok közben, így elkerülhető az esetleges emberi hiba. Minden ciklus biztosítja sterilizálás B típusú terhelést. Minden sterilizálási eljárás frakcionált vákuum rendszerrel. ",
    desc4: "Ergonomikus és egyszerű a használata. Bármilyen működési hibát hibaüzenettel jelez. Maximális üzembiztonságot nyújtja. Szintén elérhető a Model 24 literes változatban. Ez a modell különösen alkalmas a közepes és nagy létesítményekre, klinikáknak és központoknak. ",
    desc5: "Europe B PRO24 rendszer fel van szerelve fordított ozmózis móddal is. ",
    desc6: "Maximálisam biztosítékok: 10 A Tápfeszültség jelentése: 50-60 Hz Maximális elektromos elnyelt: 1700 W Nettó tömege termék: 61 Kg Termék szélessége: 504mm. Termék magassága: 400mm. Termék mélysége: 640mm. Kezdő év a gyártási és forgalmazási: 2011",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Fóliahegesztő Millseal Plus",
    image: "/images/millseal.jpeg",
    slug: "produktum 27",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "Manuális fóliahegesztő, a felhasználó választja meg a zacskó hosszát, vágja le azt és forrasztja le a zacskó végét. Folyamatos ciklus, állandó hőmérséklet. Fűtőrész hőmérséklete: 180°C",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Stillo asztali vízdesztilláló",
    image: "/images/stillo.jpg",
    slug: "produktum 28",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "Működése: Amikor a desztilláló be van kapcsolva, a víz hőmérséklete fokozatosan emelkedik és a vegyi anyagok, nehézfémek és egyéb szennyeződések a rozsdamentes acél tartály alján maradnak, így a szennyeződéseket és a kellemetlen szagokat eltávolítja. A gőz összegyűlik a hűtőcsatorna felületén, amely desztillált vízcseppeket képez és áthalad az aktivált faszén tasakon.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Nyomtató",
    image: "/images/nyomtato.jpeg",
    slug: "produktum 29",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "Opcionális kiegészítő autoklávokhoz. Külső nyomtató, mellyel jelentéseket vagy vonalkód matricákat lehet készíteni.",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "Pure víztisztító",
    image: "/images/pure.jpg",
    slug: "produktum 30",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "Pure 100: Demineralizáló 2 ion-cserélő gyanta patronnal. Kiküszöböl minden szennyezett iont, amely jelen van a vízben, hogy magas minőségű demineralizált vizet biztosítson. mPure 500: ökológiai fordított ozmózisos demineralizáló rendszer, mely ellátja az autoklávot demineralizált vízzel; a víz egy ozmotikus membránon megy keresztül annak érdekében, hogy a sterilizálás ideális feltételeit biztosítsa",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Szoftver",
    image: "/images/szoftver.jpeg",
    slug: "produktum 31",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "A MyTrace a Cefla nyomon követési szoftvere, mely a PLATINUM sorozat tartozéka (a többi modell esetében extraként kérhető). Ennek a programnak a használatával a sterilizált eszközök minden csoportja vonalkódon keresztül társítható a beteghez. Ez az alapvető szoftver befejezi a sterilizálási folyamatot és jogi védelmet nyújt a fogorvosoknak. A vonalkód olvasó extraként elérhető!",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Autokláv töltő",
    image: "/images/tolto.jpg",
    slug: "produktum 32",
    category: "Sterilizálás",
    subcategory: "Autokláv kiegészítő",
    desc: "Egy külső pumpából áll, melyet a sterilizáló működtet, ezen keresztül áramlik a víz a palackból vagy más edényből",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "Tehtys H10 Plus",
    image: "/images/TethysH10Plus.jpg",
    slug: "produktum 33",
    category: "Sterilizálás",
    subcategory: "Mosó-fertőtlenítő gép",
    desc: "A Tethys H10 Plus az új termikus fertőtlenítő, amely egyszerűvé és praktikussá teszi az eszközök tisztításának folyamatát. Ez az innovatív eszköz a sterilizálás előtt felmerülő számos – jellemzően kézi feladat – nagy részét elvégzi, ezáltal csökkentve a személyzet terhelését és a kockázatot.", 
    desc2: "A Tethys H10 Plus által a szennyeződésmentesítés, a mosás, a termikus fertőtlenítés és a szárítás egy gyors, automatizált folyamattá válik.",
    desc3: "4 az 1-ben megoldás:",
    desc4: "1. Szennyeződésmentesítés –  az eszközön lévő baktériumok számának csökkentése", 
    desc5: "2. Ultrahangos-tisztítás – szerves és szervetlen maradványok eltávolítása az eszközökről", 
    desc6: "3. Termikus fertőtlenítés – az eszközökön élő mikroorganizmusok számának drasztikus csökkentése", 
    desc7: "4. Forró levegős szárítás – a gőz és a maradék nedvesség eltávolítása a tartályból és a műszerekről. ",
    desc8: "Műszaki jellemzők:színes LCD kijelző egyértelmű ikonokkal,belső memória, USB csatlakozóval az adatok mentéséhez,6 program: 3 gyári és 3 személyre-szabható,külső méretek: 470*430*500 mm,súly: 37kg, max. töltési súly: 2kg,tartály effektív kapacitása: 6 liter, max. vízfelhasználás: 15 liter/ciklus.",
    amount: 1,
    price: 0 
  },
  {
    _id: uuidv4(),
    name: "SW GoldSpeed Evo D1,D1-L",
    image: "/images/evod1l.jpeg",
    slug: "produktum 34",
    category: "Kézidarabok",
    subcategory: "Egyenesdarab",
    desc: " Egyenes kézidarab általános fogászati célra.", 
    desc2: " 1:1 áttétel. Egyszeres spray. Autoklávozható.",
    desc3: "Fénnyel vagy fény nélkül.",
    amount: 1,
    price: 0
  },
  {
    _id: uuidv4(),
    name: "NSK M65",
    image: "/images/M65.jpg",
    slug: "produktum 35",
    category: "Kézidarabok",
    subcategory: "Egyenesdarab",
    desc: "Áttétel 1:1 Direkt vezetés.",
    desc2: "HP fúrószárhoz (Ø2.35) / CA fúrószárhoz (Ø2.35) ",
    desc3: "Egyszeres Sprayhűtés.",
    desc4: "* Biztosított fúrószár rögzítő beszerelése szükséges.",
    desc5: "Rozsdamentes acél test.",
    desc6: "Max Fordulat 40,000 min-1.",
    desc7: "Üvegszálas optika",
    desc8: "Tiszta fejrendszer",
    desc9: "* Biztosított fúrószár rögzítő beszerelése szükséges.",
    amount: 1,
    price: 188580,
  },
  {
    _id: uuidv4(),
    name: "NSK Nano65LS",
    image: "/images/Nano65LS.jpg",
    slug: "produktum 36",
    category: "Kézidarabok",
    subcategory: "Egyenesdarab",
    desc: "Rövidebb, könnyebb a tökéletesen kiegyensúlyozott “nano sorozat” műszerei úgy lettek tervezve, hogy megfelelően illeszkedjen a kezébe biztosítva az eljárások gördülékeny menetét. A finom és pontos mozgást igénylő implantációs műveletek során a “nano sorozat” hűen tükrözi a felhasználó szándékát.",
    desc2: "Áttétel – 1:1 Direkt vezetés.",
    desc3: "HP / CA fúrószárhoz (Ø2.35) *Biztosított fúrószár rögzítő beszerelése szükséges.",
    desc4: "Egyszeres Sprayhűtés.",
    desc5: "Titánium burkolat DURACOAT® bevonattal.",
    desc6: "Fordulat – 40,000 min-1.",
    desc7: "Üvegszálas optika / Tiszta fejrendszer.",
    amount: 1,
    price: 362040,
  },
  {
    _id: uuidv4(),
    name: "NSK X65L",
    image: "/images/x65l.jpg",
    slug: "produktum 37",
    category: "Kézidarabok",
    subcategory: "Egyenesdarab",
    desc: "LED fényes.",
    desc2: "Áttétel 1:1 Direkt vezetés", 
    desc3: "HP fúrószárhoz (Ø2.35) / CA fúrószárhoz (Ø2.35) * Biztosított fúrószár rögzítő beszerelése szükséges", 
    desc4: "Egyszeres Sprayhűtés", 
    desc5: "Titánium burkolat DURACOAT® bevonattal.", 
    desc6: "Fordulat 40,000 min-1",
    amount: 1,
    price: 353640,
  },
  {
    _id: uuidv4(),
    name: "NSK X65",
    image: "/images/x65l.jpg",
    slug: "produktum 38",
    category: "Kézidarabok",
    subcategory: "Egyenesdarab",
    desc: "LED fény nélküli.",
    desc2: "Áttétel 1:1 Direkt vezetés", 
    desc3: "HP fúrószárhoz (Ø2.35) / CA fúrószárhoz (Ø2.35) * Biztosított fúrószár rögzítő beszerelése szükséges", 
    desc4: "Egyszeres Sprayhűtés", 
    desc5: "Titánium burkolat DURACOAT® bevonattal.", 
    desc6: "Fordulat 40,000 min-1",
    amount: 1,
    price: 213780,
  },
  {
   _id: uuidv4(),
    name: "NSK Endo-Mate TC2 MPA",
    image: "/images/endomatetc2.jpg",
    slug: "produktum 39",
    category: "Kézidarabok",
    subcategory: "Endodoncia",
    desc: "Endodonciás mikromotor",
    desc2: "Vezeték nélkül", 
    desc3: "5 egyedi tárolható program", 
    desc4: "Nagy méretű LCD kijelző", 
    desc5: "90 perces gyors feltöltés", 
    desc6: "Könnyű, ergonómikus kialakítású",
    desc7:" Pontos sebesség és nyomatékszabályozás",
    desc8: "Automatikus oda-vissza funkció",
    desc9: "Egyszerű kezelés és felhasználóbarát működés",
    desc10: "Apex lokátorhoz csatlakoztatható!",
    desc11: "A csomag tartalma:",
    desc12: "1 db Endo – Mate TC2-es motor",
    desc13: "1 db töltő",
    desc14: "1 db MP-F16R fej",
    amount: 1,
    price: 544320,
  },
  {
   _id: uuidv4(),
    name: "NSK IpexII apexlokátor",
    image: "/images/ipexII.jpg",
    slug: "produktum 40",
    category: "Kézidarabok",
    subcategory: "Endodoncia",
    desc: "Fejlett Apex Locator.",
    desc2: "Számos klinikai vizsgálat és ellenőrző teszt alapján, az NSK létrehozta a  SmartLogic-t, a következő generációs Apex Locatiort, amely kompatibilis  különböző fogformákkal, és kiváló pontosságot biztosít a gyökércsúcs észlelésében.",
    desc3: "A biológiailag meghatározó gyökércsúcson – a Precíziós Zónában – az iPex egyértelmű és pontos képet adhat a fájl tippéről az LCD panelen.",
    desc4: "A csomag tartalma:",
    desc5: "Vezérlőegység / iPexII Kábel (1,8m) / iPexII Klip (3 db) / Kampó (3 db) / Akkumlátor (3 db) / iPexII Vizsgáló.",
    desc6:" Jellemzők:",
    desc7: "Tápegység – 1.5V AAA (LR03 vagy R03) akkumulátor.",
    desc8: "Folyamatos használat – Kb. 60 óra.",
    desc9: "Paraméterek – 60 x 60 x 86 (mm).",
    desc10: "Súly – 76g (akkumulátor nélkül).",
    amount: 1,
    price: 356160,
  },

];

export default products;
